### ISSUE TITLE
8주차, 9주차

### ISSUE THREAD

**Issue by Min-ji99** [DewPeaceTigers/NetworkStudy#6]
18. 무선 네트워크1
19. 무선 네트워크2
20.  무선 네트워크3
21.  멀티미디어 네트워크
22. 네트워크 보안1
23. 네트워크 보안2

**Comment by Min-ji99** [comment]
## 민지 문제
1. 무선 네트워크는 충돌을 감지할 수 없기 때문에 ___을 사용한다.
2. 무선 네트워크의 MAC Protocol은 무엇인가
3. 왜 무선 네트워크 frame은 4개의 주소를 사용하는가

**Comment by kinnyeri** [comment]
## 예리 문제
1. CSMA/CA에서 채널을 차지하기 전에 보내는 것은?
2. Mobility의 의미는?
